modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/RFToolsControl/issues"
displayURL="http://github.com/McJtyMods/RFToolsControl/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="rftoolscontrol"
version="${file.jarVersion}"
displayName="RFToolsControl"
#updateJSONURL="http://myurl.me/" #optional
description='''
Visual programming language for automation
'''
[[dependencies.rftoolscontrol]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolscontrol]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4.1.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.rftoolscontrol]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.15-1.1.6,)"
    ordering="AFTER"
    side="BOTH"