modLoader="javafml"
loaderVersion="[33,)"
license="MIT License https://github.com/McJtyMods/RFToolsControl/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/RFToolsControl/issues"
displayURL="http://github.com/McJtyMods/RFToolsControl/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="rftoolscontrol"
version="${file.jarVersion}"
displayName="RFToolsControl"
#updateJSONURL="http://myurl.me/" #optional

description='''
Visual programming language for automation
'''
[[dependencies.rftoolscontrol]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolscontrol]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.16-5.0.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.rftoolscontrol]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.16-2.0.2,)"
    ordering="AFTER"
    side="BOTH"